package methodes;

import org.jetbrains.annotations.Contract;

public enum Couleur {

    PINK("crimson"),
    CYAN("cyan4"),
    GOLDEN("darkgoldenrod3"),
    GREEN("darkolivegreen2"),
    ORANGE("darkorange2"),
    PURPLE("darkorchid2"),
    BLUE("deepskyblue2"),
    CORALL("coral1"),
    GREEN2("chartreuse1"),
    RED("firebrick1"),
    SALMON("darksalmon"),
    LIGHTBROWN("peru"),
    GREY("snow4"),
    INDIGO("indigo"),
    BROWN("sienna4"),
    MINT("mintcream"),
    OLIVE("olivedrab"),
    DARKRED("red4"),
    DARKBROWN("maroon"),
    SLATEBLUE("slateblue"),
    LIGHTPINK("pink"),
    MAGENTA("magenta"),
    ROYALBLUE("royalblue"),
    MEDIUMBLUE("mediumblue"),
    BLACK("black"),
    A("hotpink"),
    B("thotpink1"),
    C("thotpink2"),
    D("thotpink3"),
    E("thotpink4"),
    F("indianred"),
    G("tindianred1"),
    H("tindianred2"),
    I("tindianred3"),
    J("tindianred4"),
    K("indigo"),
    L("tinvis"),
    M("tivory"),
    N("tivory1"),
    O("tivory2"),
    P("ivory3"),
    Q("tivory4"),
    R("tkhaki"),
    S("tkhaki1"),
    T("tkhaki2"),
    U("khaki3"),
    V("tkhaki4"),
    W("tlavender"),
    X("tlavenderblush"),
    Y("tlavenderblush1"),
    Z("lavenderblush2"),
    AA("tlavenderblush3"),
    BB("tlavenderblush4"),
    CC("tlawngreen"),
    DD("tlemonchiffon"),
    EE("lemonchiffon1"),
    FF("tlemonchiffon2"),
    GG("tlemonchiffon3"),
    HH("tlemonchiffon4"),
    II("tlightblue"),
    JJ("lightblue1"),
    KK("tlightblue2"),
    LL("tlightblue3"),
    MM("tlightblue4"),
    NN("tlightcoral"),
    OO("lightcyan"),
    PP("tlightcyan1"),
    QQ("tlightcyan2"),
    RR("tlightcyan3"),
    SS("tlightcyan4"),
    TT("lightgoldenrod"),
    UU("tlightgoldenrod1"),
    VV("tlightgoldenrod2"),
    WW("tlightgoldenrod3"),
    XX("tlightgoldenrod4"),
    YY("lightgoldenrodyellow"),
    ZZ("tlightgray"),
    AAA("tlightgrey"),
    BBB("tlightpink"),
    CCC("tlightpink1"),
    DDD("lightpink2"),
    EEE("tlightpink3"),
    DARKBLUE("navyblue");

    private String c;

    Couleur(String c) {
        this.c = c;
    }

    @Contract(pure = true)
    public String getC() {
        return c;
    }
}
